language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"
  - "2.6"

install:
  - pip install tox
  - pip install coveralls
  - pip install python-coveralls

script:
  - tox

after_script:
  - coveralls
