language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install python-coveralls

script:
  - make coverage

after_script:
  - coveralls
